// This file is generated by Velite

import type __vc from '../velite.config.js'

type Collections = typeof __vc.collections

export type Development = Collections['development']['schema']['_output']
export declare const development: Development[]

export type BookReview = Collections['bookReview']['schema']['_output']
export declare const bookReview: BookReview[]

export type PersonalEssay = Collections['personalEssay']['schema']['_output']
export declare const personalEssay: PersonalEssay[]
